#se basa en una imagen
FROM python:3.7.0-alpine

#dependencias para la base de datos
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

#establecemos el directorio de trabajo
WORKDIR /usr/src/app

#copiamos e intalamos las dependencias

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt


#nuevo
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

#copiamos app
COPY . /usr/src/app

# run server
# CMD python manage.py run -h 0.0.0.0 --port 7000

# CMD ["/usr/src/app/entrypoint.sh"]
CMD ["sh","-c","chmod 755 /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"]



